device: cuda # cuda / cpu / mps (using `transformers` as backend)
weights:
  PP-DocLayoutV2: Structure/PP-DocLayoutV2
  layoutreader_v20: Relation
models_dir: model_weight
layout_config:
  model: PP-DocLayoutV2
  reader:
    name: layoutreader_v20
chat_config:
  weight_path: model_weight/Recognition
  backend: lmdeploy # lmdeploy / vllm / transformers / api / lmdeploy_queue / vllm_queue / vllm_async
  data_parallelism: 1 # for lmdeploy only (test)
  model_parallelism: 1 # for lmdeploy and vllm
  batch_size: 10 # active when using `transformers` as backend
  # if using xxx_queue as backend
  queue_config:
    max_batch_size: 256 # maximum batch size for internal processing
    queue_timeout: 1 # seconds to wait for batching requests
    max_queue_size: 2000 # maximum requests in queue

# Uncomment the following lines if use `api` as backend 
# api_config:
#   url: https://api.openai.com/v1
#   model_name: gpt-4.1
#   api_key: sk-xxx
